name: stage

on:
  push:
    branches:
      - stage

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Gdetram clone
      uses: actions/checkout@v2

    - name: Plato clone
      uses: actions/checkout@v2
      with:
        repository: oybek/plato
        token: ${{ secrets.ACCESS_TOKEN }}
        path: 'plato/'

    - name: Cache ivy
      uses: actions/cache@v1
      env:
        cache-name: cache-ivy
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test and form the coverage report
      run: |
        sbt clean coverage test
        sbt coverageReport

    - name: Sonar scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -Dsonar.login=$SONAR_TOKEN sonarScan

    - name: Assembly
      run: sbt "clean; set test in assembly := {}; assembly"

    - name: Upload to the server
      uses: garygrossgarten/github-action-scp@release
      with:
          local: target/scala-2.13/gdetram-assembly-0.1.jar
          remote: /tmp/app-stage.jar
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cp /tmp/app-stage.jar ~/dickson/app.jar
          sudo systemctl restart dickson

    - name: Inform command
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.GDETRAM_CHAT_ID }}
        token: ${{ secrets.TG_BOT_API_TOKEN }}
        message: |
          New stage is deployed 🚀
          Commit SHA = ${{ github.sha }}
