name: stage

on:
  push:
    branches:
      - stage

jobs:
  job:
    #
    runs-on: ubuntu-latest
    # include postgres service
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: gdetram clone
      uses: actions/checkout@v2

    - name: plato clone
      uses: actions/checkout@v2
      with:
        repository: oybek/plato
        token: ${{ secrets.ACCESS_TOKEN }}
        path: 'plato/'

    - name: Cache ivy
      uses: actions/cache@v1
      env:
        cache-name: cache-ivy
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    # setup jdk 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #
    - name: Compile/Test/Assembly
      run: sbt "compile; test; set test in assembly := {}; assembly"
    # copy assembled jar over ssh to vps
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: target/scala-2.12/gdetram-assembly-0.1.jar
          remote: /tmp/app-stage.jar
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
    # update remote app
    - name: Update app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cp /tmp/app-stage.jar ~/gdetram-stage/app.jar
          sudo systemctl restart gdetram-app-stage
    # report that job is done
    - name: Inform command
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.GDETRAM_CHAT_ID }}
        token: ${{ secrets.TG_BOT_API_TOKEN }}
        message: |
          New stage is deployed 🚀
          Commit SHA = ${{ github.sha }}
